config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'authentication#login'

  get 'authentication/login', as: 'login'
  post 'authentication/sign_in', as: 'sign_in'

  resources :admin, only: :index

  namespace :admin do
  	 resources :scraping_sources, only: [:index, :destroy] do
  	 	collection do  
  	 		post 'add_source'
  	 		post 'edit_source'
  	 		post 'check_import'
  	 	end
  	 	resources :scraping_origins, only: :create
  	 end
  	 resources :scraping_origins, only: :show
     resources :user_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end     
     resources :campaign_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end     
     resources :counterpart_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end

     resources :users, only: :index
     resources :campaigns, only: :index
     resources :counterparts, only: :index
  end
end

app/models/scraping_source.rb
class ScrapingSource < ApplicationRecord
	has_many :scraping_origins
end

app/controllers/admin/scraping_sources_controller.rb
class Admin::ScrapingSourcesController < AdminController

	def index 
		#used in modal to show the table
		@scraping_sources = ScrapingSource.all
	end

	def add_source
		# add for different origin
		if @scraping_source = ScrapingSource.find_by(url: scraping_source_params[:url])
			render json: {success: true, exist: true, scraping_source: @scraping_source}		
		else
			@scraping_source = ScrapingSource.create(scraping_source_params)
			render json: {success: true, scraping_source: @scraping_source}		
		end
	end

	def edit_source
		@scraping_source = ScrapingSource.find(scraping_source_params[:id])
		if @scraping_source.update(scraping_source_params.except(:id))
			render json: {success: true, scraping_source: @scraping_source}
		else
			render json: {success: false}
		end
	end

	def check_import
		url = params[:scraping_url]
		@scraping_result = ScrapingService.check_import(url)
		if @scraping_result[:success]
			@scraping_source = ScrapingSource.find(@scraping_result[:scraping_data][:scraping_source_id])
			@scraping_origin = ScrapingOrigin.new
		end
	end	


	def destroy
		scraping_source = ScrapingSource.find(params[:id])
		scraping_source.destroy
		render json: {success: true}
	end

	private
	def scraping_source_params
		params.require(:scraping_source).permit!
	end

end

app/views/admin/scraping_sources/_edit_mapping_modal.html.erb
<div class="modal fade" id="editMappingModal" tabindex="-1" role="dialog" aria-labelledby="editMappingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editMappingModalLabel">Modifier un source</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <%= form_tag(edit_source_admin_scraping_sources_path, {remote: true, id: "edit_scraping_source"}) do %>
        <input type="hidden" id="edit_scraping_source_id" name="scraping_source[id]">
        <div class="form-group">
          <label>Nom </label>
          <%= text_field_tag "scraping_source[name]", nil, class: "form-control", required: true, id: "edit_scraping_source_name" %>
        </div>
        <div class="form-group">
          <label>Lien racine</label>
          <%= text_field_tag "scraping_source[url]", nil, class: "form-control", required: true, id: "edit_scraping_source_url" %>
        </div>        
        <div class="form-group">
          <label>Montant collecté</label>
          <%= text_field_tag "scraping_source[ext_collected_amount]", nil, class: "form-control", id: "edit_scraping_source_exp_ca" %>
        </div>
        <div class="form-group">
          <label>Objectif initial</label>
          <%= text_field_tag "scraping_source[ext_initial_target]", nil, class: "form-control", id: "edit_scraping_source_exp_it" %>
        </div>
        <div class="form-group">
          <label>Nombre contributeurs</label>
          <%= text_field_tag "scraping_source[ext_nb_contributors]", nil, class: "form-control", id: "edit_scraping_source_exp_nc" %>
        </div>
        <div class="form-group">
          <label>Date fin</label>
          <%= text_field_tag "scraping_source[ext_end_date]", nil, class: "form-control", id: "edit_scraping_source_exp_ed" %>
        </div>
      
      <% end -%>
      

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulé</button>
        <button id="submit_edit_scraping_source" type="button" class="btn btn-primary" data-dismiss="modal">Modifier</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/scraping_sources/_failed_scraping.html.erb
<div class="card">
  <div class="card-block">
    <p>
      Nous n'avons pas réussi à importer les données. Vueillez noter que seuls ces plateformes sont supportés: kickstarter, indiegogo, ulule, kisskissbankbank
    </p>
    <p>
      <small class="text-muted">Pour demander d'ajout d'une autre plateforme, veuillez nous contactez à support@colect.co</small>
    </p>
  </div>
</div>

app/views/admin/scraping_sources/_imported_data.html.erb
<div class="card">
  <div class="card-block">
    <p>
    	Montant Collecté : <%= scraping_data_source[:collected_amount] %><br>
    	Objectif initial : <%= scraping_data_source[:initial_target] %><br>
    	Nb Contributeurs : <%= scraping_data_source[:nb_contributors] %><br>
    </p>
    <%= form_for [:admin, scraping_source, scraping_origin], html: { class: "form-inline"} do |f| %>
      <%= f.hidden_field :link , value: scraping_data_source[:origin_url] %>
       <label class="mr-sm-2">Date fin :</label> 
       <%= f.date_field :end_date, class: "form-control", required: true %>  
       <label class="mr-sm-2">Fréquence de mise à jours</label>
	     <%= f.select :frequency, options_for_select(select_list_frequencies) , {}, class: "custom-select mb-2 mr-sm-2 mb-sm-0"%> 

	  <%= f.submit "Associer", class: "btn btn-success" %>
	<% end  %>
  </div>
</div>

app/views/admin/scraping_sources/_mapping_modal.html.erb
<div class="modal fade" id="mappingModal" tabindex="-1" role="dialog" aria-labelledby="mappingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mappingModalLabel">Scraping Sources</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <table class="table table-responsive" id="scraping_sources_table">
            <thead>
              <tr>
                <th>Site</th>
                <th>Lien racine</th>
                <th>Montant Collectés</th>
                <th>Objectif</th>
                <th>NB Contricuteurs</th>
                <th>Date de fin</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @scraping_sources.each do |sr| %>
                <tr ss-id="<%= sr.id %>">
                  <td><%= sr.name %></td>
                  <td><%= sr.url %></td>
                  <td><%= sr.ext_collected_amount %></td>
                  <td><%= sr.ext_initial_target %></td>
                  <td><%= sr.ext_nb_contributors %></td>
                  <td><%= sr.ext_end_date %></td>
                  <td><button ss-id="<%= sr.id %>" class="btn btn-primary edit_source" data-toggle="modal" data-target="#editMappingModal"><i class="fa fa-pencil-square-o"></i>
                  </button>
                  <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, admin_scraping_source_path(sr), remote: true, class: "delete-source btn btn-danger", data: {method: "delete", confirm: "Vous voulez supprimer ce mapping ?"} %>
                  </td>
                </tr>
              <% end -%>
            </tbody>
          </table>
          </div>
      

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newMappingModal">Ajouter un nouveau site</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>


<%= render partial: "new_mapping_modal" %>
<%= render partial: "edit_mapping_modal" %>

app/views/admin/scraping_sources/_new_mapping_modal.html.erb
<div class="modal fade" id="newMappingModal" tabindex="-1" role="dialog" aria-labelledby="newMappingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newMappingModalLabel">Ajouter un source</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <%= form_tag(add_source_admin_scraping_sources_path, {remote: true, id: "create_scraping_source"}) do %>
         
        <div class="form-group">
          <label>Nom </label>
          <%= text_field_tag "scraping_source[name]", nil, class: "form-control", required: true %>
        </div>
        <div class="form-group">
          <label>Lien racine</label>
          <%= text_field_tag "scraping_source[url]", nil, class: "form-control", required: true %>
        </div>        
        <div class="form-group">
          <label>Montant collecté</label>
          <%= text_field_tag "scraping_source[ext_collected_amount]", nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Objectif initial</label>
          <%= text_field_tag "scraping_source[ext_initial_target]", nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Nombre contributeurs</label>
          <%= text_field_tag "scraping_source[ext_nb_contributors]", nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Date fin</label>
          <%= text_field_tag "scraping_source[ext_end_date]", nil, class: "form-control" %>
        </div>
      
      <% end -%>
      

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulé</button>
        <button id="submit_scraping_source" type="button" class="btn btn-primary" data-dismiss="modal">Ajouter</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/scraping_sources/check_import.js.erb
<% if @scraping_result[:success] %>
	$("#import_result").html("<%=j render :partial => 'imported_data' , locals: {scraping_data_source: @scraping_result[:scraping_data], scraping_source: @scraping_source, scraping_origin: @scraping_origin} %>")
<% else %>	
	$("#import_result").html("<%=j render :partial => 'failed_scraping' %>")
<% end %>	

app/views/admin/scraping_sources/index.html.erb
<div class="container">

	<hr>
	<%= form_tag check_import_admin_scraping_sources_path , remote: true, class: "form-inline", id: "check_import_form" do %>	
		<label class="mr-sm-2" >Lien</label>
	  <%= text_field_tag "scraping_url", nil, class: "form-control col-md-8", id: "scraping_url" ,placeholder: "http://votrecompanie_url" %>

	  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mappingModal">
		  Mapping
		</button>

	<% end -%>
	<label class="custom-control custom-checkbox">
	  <input type="checkbox" class="custom-control-input" id="certified_source_checkbox">
	  <span class="custom-control-indicator"></span>
	  <span class="custom-control-description">Je certifie que je suis l'organisateur de la compagne indiqué dans ce lien</span>
	</label>
	<br>
	<button id="submit_check_import_form" type="button" class="btn btn-success" >
	  Vérifier l'import des données
	</button>

	<hr>


	<div id="import_result"></div>

</div>

<%= render partial: "mapping_modal" %>