config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'authentication#login'

  get 'authentication/login', as: 'login'
  post 'authentication/sign_in', as: 'sign_in'

  resources :admin, only: :index

  namespace :admin do
  	 resources :scraping_sources, only: [:index, :destroy] do
  	 	collection do  
  	 		post 'add_source'
  	 		post 'edit_source'
  	 		post 'check_import'
  	 	end
  	 	resources :scraping_origins, only: :create
  	 end
  	 resources :scraping_origins, only: :show
     resources :user_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end     
     resources :campaign_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end     
     resources :counterpart_migrations, only: :index do 
      collection do 
        get 'start'
        get 'show_log'
      end
     end

     resources :users, only: :index
     resources :campaigns, only: :index
     resources :counterparts, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_organization.rb
class BusinessOrganization < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	has_many :counterparts
end

app/models/counterpart.rb
class Counterpart < ApplicationRecord
	belongs_to :campaign, optional: true
end

app/models/scraping_datum.rb
class ScrapingDatum < ApplicationRecord
	belongs_to :scraping_origin

	scope :recent, ->{ order(created_at: :desc) }
	
	def self.convert_to_num str
		str.scan(/[.,0-9]/).join.gsub(/,(\d{2}$)/,'.\1').gsub(",","").to_f
	end
end

app/models/scraping_origin.rb
class ScrapingOrigin < ApplicationRecord
	belongs_to :scraping_source
	has_many :scraping_data
end

app/models/scraping_source.rb
class ScrapingSource < ApplicationRecord
	has_many :scraping_origins
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord

	has_many :social_links
	has_many :business_organizations


	# This method exist in the existing application
	def self.authenticate email, password
		user = User.find_by(email: email)
		if user.present?
			# This just a way of a simple authentication since we didn't agree on the implementation details (it's already done)
			if user.password_hash == hashed_pass(user.salt.to_s+password)
				return {status: :success, user: user}
			end
		end
		{status: :error}
	end

	def full_name
		[name,l_name].join(" ")
	end

	def address
		[lign1,lign2,cp, ville].join(" ")
	end

	private
	def self.hashed_pass password
		Digest::SHA256.hexdigest password
	end
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < AdminController

	def index
		@campaigns = Campaign.page(params[:page]).per_page(10)
	end

end

app/controllers/admin/counterparts_controller.rb
class Admin::CounterpartsController < AdminController

	def index
		@counterparts = Counterpart.page(params[:page]).per_page(10) 
	end

end

app/controllers/admin/user_migrations_controller.rb
class Admin::UserMigrationsController < AdminController

	def index
		@migration_log = File.read("#{Rails.root}/log/digisponsor_user_migration.log").gsub("\n","<br>").html_safe rescue "No log file"
		@migration_started = Digisponsor::UserService.migration_started?
	end

	def start
		# start migration job
		if Digisponsor::UserService.migration_started?
			render json: {success: false, message: "Migration Already Started"}
		else
			Digisponsor::UserService.migration_init
			Digisponsor::MigrateUserJob.perform_later
			render json: {success: true, redirect: show_log_admin_user_migrations_path}
		end
	end

	def show_log
		# show log every second
		@migration_log = File.read("#{Rails.root}/log/digisponsor_user_migration.log").gsub("\n","<br>").html_safe
		render json: {log: @migration_log.gsub("\n","<br>").html_safe, migration_finished: !Digisponsor::UserService.migration_started?}
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController


	def index
		@users = User.page(params[:page]).per_page(10) 
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	# user should have administration role
	# since this is not added in the specification document 
	# we're not going to add it

	layout 'admin'

	def index
		redirect_to admin_scraping_sources_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :user_authenticated?

  def user_authenticated?
  	if user_session.nil? && controller_name.to_sym != :authentication 
  		redirect_to login_path
  	elsif user_session.present? && controller_name.to_sym == :authentication
  		redirect_to admin_index_path
  	end
  end

  protected
  def set_user_session user_id
  	session[:user_id] = user_id
  end

  private
  def user_session
  	session[:user_id]
  end	


end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController


	def sign_in
		result = User.authenticate user_params[:email], user_params[:password]
		if result[:status] == :success
			set_current_user result[:user] 
			redirect_to admin_index_path, notice: "Authenticated Successfully"
		else
			flash[:alert] = "Wrong email or password"
			render :login
		end 
	end

	def set_current_user user
		set_user_session user.id
	end

	private
	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController






end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/pagination_helper.rb
require "will_paginate/view_helpers/action_view"

module PaginationHelper

  module BootstrapRenderer

    def to_html
      html = pagination.map do |item|
        item.is_a?(Fixnum) ?
          page_number(item) :
          send(item)
      end.join(@options[:link_separator])

      html = html_container(html) if @options[:container]

      tag("nav", tag("ul", html, class: @options[:class]))
    end

    protected

    def page_item(text, url, link_status = nil)
      text = text.to_s + tag(:span, "(current)", class: "sr-only") if link_status == "active"
      link_tag = link_status.nil? ? link(text, url, class: "page-link", rel: text) : tag(:span, text, class: "page-link")

      tag(:li, link_tag, class: "page-item #{link_status}")
    end

    def page_number(page)
      link_status = "active" if page == current_page
      page_item(page, page, link_status)
    end

    def gap
      text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
      page_item(text, nil, "disabled")
    end

    def previous_page
      num = @collection.current_page > 1 && @collection.current_page - 1
      previous_or_next_page(num, @options[:previous_label], "Previous")
    end

    def next_page
      num = @collection.current_page < total_pages && @collection.current_page + 1
      previous_or_next_page(num, @options[:next_label], "Next")
    end

    def previous_or_next_page(page, text, aria_label)
      link_status = "disabled" unless page
      page_item(text, page, link_status)
    end
  end
end

WillPaginate::ActionView::LinkRenderer.send :include, PaginationHelper::BootstrapRenderer

app/helpers/scraping_helper.rb
module ScrapingHelper
	def select_list_frequencies 
		[["1 min",1],["5 min",5],["60 min",60],["Une seule fois",0]]
	end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MigrationScraping</title>
    <%= csrf_meta_tags %>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  	<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
		  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <a class="navbar-brand" href="#">M-Scraping</a>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		      	<%= link_to "Scraping", admin_scraping_sources_path , class: "nav-link" %>
		      </li>
		      <li class="nav-item">
		      	<%= link_to "Historiques", (admin_scraping_origin_path(ScrapingOrigin.first) rescue "#") , class: "nav-link" %>
		      </li>
		       <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Migration
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		          <%= link_to "Utilisateurs", admin_user_migrations_path, class: "dropdown-item" %>
		          <%= link_to "Campagne", admin_campaign_migrations_path, class: "dropdown-item" %>
		          <%= link_to "Contreparties", admin_counterpart_migrations_path, class: "dropdown-item" %>
		        </div>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Données
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		          <%= link_to "Utilisateurs", admin_users_path, class: "dropdown-item" %>
		          <%= link_to "Campagne", admin_campaigns_path, class: "dropdown-item" %>
		          <%= link_to "Contreparties", admin_counterparts_path, class: "dropdown-item" %>
		        </div>
		      </li>
		   
		    </ul>
		  </div>
		</nav>

    

    	<%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MigrationScraping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<% if notice %>
		  	<div class="alert alert-success">
			  <strong>Success!</strong> <%= notice %>
			</div>
		<% end -%>
		<% if alert %>
			<div class="alert alert-danger">
			  <strong>Error!</strong> <%= alert %>
			</div>
		<% end -%>
	</div>

    <%= yield %>
  </body>
</html>